_target_: terratorch.tasks.MultiLabelClassificationTask
model_factory: EncoderDecoderFactory
model_args:
  backbone: timm_convnextv2_atto
  backbone_pretrained: False
  backbone_in_chans: 14
  decoder: IdentityDecoder
  num_classes: ???
loss: bce
ignore_index: -1
freeze_backbone: false
freeze_decoder: false
optimizer: AdamW
lr: 1.e-4
optimizer_hparams: {}
