# lightning.pytorch==2.1.1	-	-	Already completed
seed_everything: 0
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: bf16-mixed
  logger:
    class_path: TensorBoardLogger
    init_args:
      save_dir: experiments
      name: levircdplus
  callbacks:
    - class_path: TQDMProgressBar
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: epoch

  max_epochs: 100 
  check_val_every_n_epoch: 1
  log_every_n_steps: 10
  enable_checkpointing: true
  default_root_dir: experiments
data:
  class_path: torchgeo.datamodules.LEVIRCDPlusDataModule
  init_args:
    batch_size: 16
    patch_size: 1024
    val_split_pct: 0.2
    num_workers: 8
  dict_kwargs:
    root: data/levircdplus
    download: true

model:
  class_path: eosfm.tasks.ChangeDetectionTask
  init_args:
    model_factory: ChangeDetectionEncoderDecoderFactory
    model_args:
      backbone: timm_convnextv2_atto
      backbone_pretrained: True
      decoder: UperNetDecoder
      decoder_channels: 128
      head_channel_list: [128]
      head_dropout: 0.1
      num_classes: 2  # Binary: no change / change
    loss: ce
    ignore_index: -1
